Гусев Михаил, поле для шахмат, гр. 3530901/20003
Saloed/softdev-2023-spring-task-1 pull request #7
Opened 2023-03-01 21:05 UTC by Chrisnisch

2023-03-03 08:19 UTC, Saloed requested changes

2023-03-03 08:19 UTC, Saloed commented on task/src/main/java/task1/ChessBoard.java
> +    protected static final String[] availablePieces = {
Лучше использовать для этого `enum`

2023-03-03 08:19 UTC, Saloed commented on task/src/main/java/task1/ChessBoard.java
> +    private String message;
Можно просто передать `message` в конструктор super класса. Можно не заводить поле

2023-03-03 08:19 UTC, Saloed commented on task/src/main/java/task1/ChessBoard.java
> +    public String toString(String s) {
`toString` выглядит немного не так. Он не должен ничего принимать. Ну и в вашем случае его можно не переопределять.

2023-03-03 08:19 UTC, Saloed commented on task/src/main/java/task1/ChessBoard.java
> +                switch (curPiece) {
Если проверять корректность ходов, то там вроде чуть больше правил

2023-03-03 08:19 UTC, Saloed commented on task/src/main/java/task1/ChessBoard.java
> +    protected String[][] board = {
Лучше использовать не строки, а, например, `Piece`

2023-03-03 08:26 UTC, Chrisnisch commented on task/src/main/java/task1/ChessBoard.java
> +                switch (curPiece) {
я не стал соблюдать правила ходов, только то, что клетка свободна

2023-03-03 13:26 UTC, Chrisnisch commented on task/src/main/java/task1/ChessBoard.java
> +    protected String[][] board = {
Не придумал как реализовать через Piece

2023-03-06 10:24 UTC, Saloed requested changes

2023-03-06 10:24 UTC, Saloed commented on task/src/main/java/task1/ChessBoard.java
> +class Piece {
Так а зачем ва этот класс, если у вас есть enum `AvailablePieces`? Если вы хотите, чтобы у фигуры имя было красивое, то просто добавьте поле в `enum`.

2023-03-09 16:23 UTC, Saloed commented on task/src/main/java/task1/ChessBoard.java
> +                for (Piece[] line : board) {
Подобный цикл дублируется много раз. Лучше сделать его отдельной функцией

2023-03-09 18:34 UTC, Chrisnisch commented on task/src/main/java/task1/ChessBoard.java
> +    private void kingChecking(String name, int x, int y) throws PutException {
Если ставится белый король, то в параметр пойдёт чёрный и наоборот. Тип строка и название имя, потому что это было сделано, до исправления на enum, но в итоге и сейчас работает как надо

2023-03-13 10:04 UTC, Saloed approved these changes

2023-03-13 10:04 UTC, closed without merging